# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# 2 control plane node and 2 workers
nodes:
# the control plane node config
- role: control-plane
  image: kindest/node:v1.27.1
- role: worker
  image: kindest/node:v1.27.1
- role: worker
  image: kindest/node:v1.27.1
